# Generated by Django 2.0.3 on 2021-02-27 19:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_url', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('post_date_time', models.DateField(blank=True)),
                ('images', models.FileField(upload_to='service_images/')),
                ('image_alt_tag', models.CharField(blank=True, max_length=200)),
                ('details', ckeditor.fields.RichTextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True)),
                ('ordering', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'all_job',
                'verbose_name_plural': 'all_jobs',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=200)),
                ('ordering', models.IntegerField(default=0)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'catagories',
            },
        ),
        migrations.CreateModel(
            name='SeoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_meta_title', models.TextField(blank=True)),
                ('index_meta_description', models.TextField(blank=True)),
                ('index_meta_keywords', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seo Content',
                'verbose_name_plural': 'Seo Contentes',
            },
        ),
        migrations.AddField(
            model_name='all_job',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category'),
        ),
    ]
