# Generated by Django 2.0.3 on 2021-08-26 15:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='govcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govcategory_details', ckeditor.fields.RichTextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'govcategory',
                'verbose_name_plural': 'govcategory',
            },
        ),
    ]
