# Generated by Django 2.0.3 on 2021-08-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_govcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='govcategory',
            options={'verbose_name': 'govcategory', 'verbose_name_plural': 'govcategories'},
        ),
        migrations.RenameField(
            model_name='govcategory',
            old_name='govcategory_details',
            new_name='govcat_details',
        ),
    ]
